-- Payment-Integrity rules, in SQL (SQLite dialect).
-- GENERATED by `make sql-dump` from app/detect_sql.py + app/reference.py.
-- Do not hand-edit: the reference data (distinct-service modifiers, panel map)
-- is the single source of truth, so edit those and regenerate.
-- Each query returns: claim_line_id, rule_id, confidence.

-- DUP-01  duplicate (parity with app/detect.py) --
    WITH g AS (
        SELECT
            line_id, allowed_amount, units,
            (SELECT COUNT(*) FROM json_each(claim.modifiers) WHERE value IN ('59', '76', '77', '91', 'LT', 'RT')) AS n_distinct,
            ROW_NUMBER()          OVER w AS rn,
            FIRST_VALUE(allowed_amount) OVER w AS orig_allowed,
            FIRST_VALUE(units)          OVER w AS orig_units
        FROM claim
        WINDOW w AS (
            PARTITION BY member_id, provider_id, cpt_code, date_of_service
            ORDER BY submitted_date, line_id
        )
    )
    SELECT
        line_id AS claim_line_id,
        'DUP-01' AS rule_id,
        CASE WHEN allowed_amount = orig_allowed AND units = orig_units
             THEN 0.95 ELSE 0.85 END AS confidence
    FROM g
    WHERE rn > 1 AND n_distinct = 0
    

-- UNB-01  unbundling (parity) --
    WITH comp(panel, component) AS (VALUES ('80061', '82465'), ('80061', '83718'), ('80061', '84478'), ('80053', '82040'), ('80053', '84075'), ('80053', '84450')),
    psize AS (SELECT panel, COUNT(*) AS n FROM comp GROUP BY panel),
    cl AS (
        SELECT c.line_id, c.member_id, c.provider_id, c.date_of_service, c.cpt_code,
               comp.panel,
               (SELECT COUNT(*) FROM json_each(c.modifiers) WHERE value IN ('59', '76', '77', '91', 'LT', 'RT')) AS n_distinct
        FROM claim c JOIN comp ON c.cpt_code = comp.component
    ),
    grp AS (
        SELECT member_id, provider_id, date_of_service, panel,
               COUNT(DISTINCT cpt_code) AS distinct_comps,
               SUM(CASE WHEN n_distinct = 0 THEN 1 ELSE 0 END) AS n_nondistinct
        FROM cl
        GROUP BY member_id, provider_id, date_of_service, panel
    )
    SELECT cl.line_id AS claim_line_id, 'UNB-01' AS rule_id, 0.90 AS confidence
    FROM cl
    JOIN grp   USING (member_id, provider_id, date_of_service, panel)
    JOIN psize USING (panel)
    WHERE grp.distinct_comps = psize.n   -- the whole panel is present
      AND grp.n_nondistinct > 0          -- not every component asserts a distinct service
    

-- OON-01  oon_mismatch (parity) --
    SELECT line_id AS claim_line_id, 'OON-01' AS rule_id, 0.92 AS confidence
    FROM claim
    WHERE provider_network_status = 'out'
      AND paid_as_network = 'in'
      AND auth_or_emergency = 0
    

-- DUP-02  date-drift duplicate (gap) — self-join form --
    SELECT a.line_id AS claim_line_id, 'DUP-02' AS rule_id, 0.80 AS confidence
    FROM claim a
    WHERE (SELECT COUNT(*) FROM json_each(a.modifiers) WHERE value IN ('59', '76', '77', '91', 'LT', 'RT')) = 0
      AND EXISTS (
          SELECT 1 FROM claim b
          WHERE b.member_id = a.member_id
            AND b.provider_id = a.provider_id
            AND b.cpt_code = a.cpt_code
            AND b.line_id <> a.line_id
            AND ABS(julianday(a.date_of_service) - julianday(b.date_of_service)) = 1
            AND (b.submitted_date < a.submitted_date
                 OR (b.submitted_date = a.submitted_date AND b.line_id < a.line_id))
      )
    

-- DUP-02  date-drift duplicate (gap) — LAG form (canonical) --
    WITH o AS (
        SELECT line_id, date_of_service, modifiers,
               LAG(date_of_service) OVER w AS prev_dos
        FROM claim
        WINDOW w AS (
            PARTITION BY member_id, provider_id, cpt_code
            ORDER BY submitted_date, line_id
        )
    )
    SELECT line_id AS claim_line_id, 'DUP-02' AS rule_id, 0.80 AS confidence
    FROM o
    WHERE prev_dos IS NOT NULL
      AND ABS(julianday(date_of_service) - julianday(prev_dos)) = 1
      AND (SELECT COUNT(*) FROM json_each(o.modifiers) WHERE value IN ('59', '76', '77', '91', 'LT', 'RT')) = 0
    

-- UNB-02  partial unbundling (gap) --
    WITH comp(panel, component) AS (VALUES ('80061', '82465'), ('80061', '83718'), ('80061', '84478'), ('80053', '82040'), ('80053', '84075'), ('80053', '84450')),
    psize AS (SELECT panel, COUNT(*) AS n FROM comp GROUP BY panel),
    cl AS (
        SELECT c.line_id, c.member_id, c.provider_id, c.date_of_service, c.cpt_code,
               comp.panel,
               (SELECT COUNT(*) FROM json_each(c.modifiers) WHERE value IN ('59', '76', '77', '91', 'LT', 'RT')) AS n_distinct
        FROM claim c JOIN comp ON c.cpt_code = comp.component
    ),
    grp AS (
        SELECT member_id, provider_id, date_of_service, panel,
               COUNT(DISTINCT cpt_code) AS distinct_comps,
               SUM(CASE WHEN n_distinct = 0 THEN 1 ELSE 0 END) AS n_nondistinct
        FROM cl
        GROUP BY member_id, provider_id, date_of_service, panel
    )
    SELECT cl.line_id AS claim_line_id, 'UNB-02' AS rule_id, 0.75 AS confidence
    FROM cl
    JOIN grp   USING (member_id, provider_id, date_of_service, panel)
    JOIN psize USING (panel)
    WHERE grp.distinct_comps >= 2
      AND grp.distinct_comps < psize.n    -- partial, not the whole panel (that is UNB-01)
      AND grp.n_nondistinct > 0
    
